### ISSUE TITLE
Compatibility Issues with PHP 8.3

### ISSUE THREAD

**Issue by krlmrr** [tighten/duster#134] opened 2023-11-27 01:31 UTC
Steps to reproduce : 

Running duster fix / lint with PHP 8.3 with throw the following error.

<img width="1024" alt="image" src="https://github.com/tighten/duster/assets/34105282/ab0e282b-46fb-41de-91cc-b74fab6f7803">

**Comment by sabina1997** [comment] 2023-11-28 14:00
@krlmrr im having the same error on php 8.1

<img width="780" alt="image" src="https://github.com/tighten/duster/assets/41695168/930626a5-767a-4347-ac72-fca84806295c">

**Comment by krlmrr** [comment] 2023-11-28 14:13
> @krlmrr im having the same error on php 8.1
> 
> <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/41695168/286276143-930626a5-767a-4347-ac72-fca84806295c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODA4ODYsIm5iZiI6MTcwMTE4MDU4NiwicGF0aCI6Ii80MTY5NTE2OC8yODYyNzYxNDMtOTMwNjI2YTUtNzY3YS00MzQ3LWFjNzItZmNhODQ4MDYyOTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE0MDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1N2VhMjg5NzYyMWVhODgxNDYwNDZkYmZmZmQ1YjA2MDg1M2ZmNzJiYTljOWI2MzI3NWI1Nzc4MjdlODlmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ovFU0SpMMDYyuagkfGUlRj-RU3slVKH6WszOv2GKhHc">

Interesting, if I set PHP Monitor to PHP 8.2 the error goes away, but I am not able to recreate the error with PHP 8.1.

**Comment by sabina1997** [comment] 2023-11-28 14:41
@krlmrr Im not able to reproduce it locally btw, only on github CI

**Comment by GussRw** [comment] 2023-11-28 19:29
Workaround, replace `uses: tighten/duster-action@v2` with   `run: vendor/bin/duster lint`

**Comment by nowocynEmfits** [comment] 2023-11-29 09:53
I also getting this error inside gitlab ci with `vendor/bin/duster lint` via php 8.3. On php 8.2 there is no error at all.

**Comment by Bottelet** [comment] 2023-11-29 14:47
If you are using the duster-action I believe this is the problem:
https://github.com/tighten/duster-action/issues/7#issuecomment-1832035664

Hopefully, we can get a fix, with a fixed version, or PHP 8.3 compatibility.

**Comment by negoziator** [comment] 2023-11-30 11:52
+1 Bump 

@mattstauffer  - Would you have a second for this?  😄

**Comment by mattstauffer** [comment] 2023-11-30 21:10
I've asked the Tighten folks who are helping me with Duster to take a look!

**Comment by mattstauffer** [comment] 2023-11-30 21:10
and... @driftingly is on the case.

Honestly I shouldn't even say "helping" at this point lol. Anthony runs things.

**Comment by driftingly** [comment] 2023-12-01 18:47
Hey everyone, this has been fixed in [2.6.0](https://github.com/tighten/duster/releases/tag/v2.6.0). Thank you for reporting and patience 🙏

**Closed as completed by driftingly** 2023-12-01 18:47 UTC

**Comment by krlmrr** [comment] 2023-12-03 06:26
Can confirm, this bug is fixed!
